// "use client";
import ".././globals.css";
import LeftSidebar from "@/components/LeftSidebar";
import Loader from "@/components/Loader";
import RightSidebar from "@/components/RightSidebar";
import { ClerkProvider, ClerkLoaded, ClerkLoading } from "@clerk/nextjs";

export const metadata = {
  title: "Social media Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ClerkLoading>
            <Loader />
          </ClerkLoading>
          <ClerkLoaded>
            <div className="flex justify-between max-w-6xl mx-auto">
              <div className="hidden sm:inline border-r h-screen sticky top-0">
                <LeftSidebar />
              </div>
              <div className="max-w-2xl flex-1">{children}</div>
              <div className="lg:flex-col p-3 h-screen border-l hidden lg:flex w-[24rem]">
                <RightSidebar />
              </div>
            </div>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
